/*
    Generated by Fivem Typescript Boilerplate by Whitigol#2122
*/

import { ConfigD } from "../../types/config";

const Config: ConfigD = JSON.parse(
    LoadResourceFile(GetCurrentResourceName(), "config.json")
);
